//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Custom
{
   
public partial class TbPlayerData_Character
{
    private readonly Dictionary<int, Custom.PlayerData_Character> _dataMap;
    private readonly List<Custom.PlayerData_Character> _dataList;
    
    public TbPlayerData_Character(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Custom.PlayerData_Character>();
        _dataList = new List<Custom.PlayerData_Character>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Custom.PlayerData_Character _v;
            _v = Custom.PlayerData_Character.DeserializePlayerData_Character(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Custom.PlayerData_Character> DataMap => _dataMap;
    public List<Custom.PlayerData_Character> DataList => _dataList;

    public Custom.PlayerData_Character GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Custom.PlayerData_Character Get(int key) => _dataMap[key];
    public Custom.PlayerData_Character this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}