//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.GameMain
{
   
public partial class TbLevelData
{
    private readonly Dictionary<int, GameMain.LevelData> _dataMap;
    private readonly List<GameMain.LevelData> _dataList;
    
    public TbLevelData(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, GameMain.LevelData>();
        _dataList = new List<GameMain.LevelData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameMain.LevelData _v;
            _v = GameMain.LevelData.DeserializeLevelData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, GameMain.LevelData> DataMap => _dataMap;
    public List<GameMain.LevelData> DataList => _dataList;

    public GameMain.LevelData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameMain.LevelData Get(int key) => _dataMap[key];
    public GameMain.LevelData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}